### ISSUE TITLE
Serializer produce wrong sql statement when using `.group(by:)` and `.sort(_:)` together.

### ISSUE THREAD

**Issue by IsaacXen** [vapor/database-kit#32]
Serializer produce wrong sql statement when using `.group(by:)` and `.sort(_:)` together.

### Steps to reproduce

    SomeModel.query(on: req)
        .group(by: \.id)
        .sort(\Book.id)
        .all()

### Expected behavior

    SELECT * FROM `some_model`
    GROUP BY `some_model`.`id`
    ORDER BY `some_model`.`id`;

`GROUP BY` before `ORDER BY`.

### Actual behavior

    SELECT * FROM `some_model`
    ORDER BY `some_model`.`id`
    GROUP BY `some_model`.`id`;

`ORDER BY` before `GROUP BY`.

### Possible Cause

In [SQLSerializer+DataQuery.swift [Line: 61]](https://github.com/vapor/database-kit/blob/master/Sources/SQL/Serialization/SQLSerializer%2BDataQuery.swift#L61),

    if !query.orderBys.isEmpty {
        statement.append(serialize(orderBys: query.orderBys))
    }

was execute before

    if !query.groupBys.isEmpty {
        statement.append(serialize(groupBys: query.groupBys))
    }

**Comment by tanner0101** [comment]
Hi @IsaacXen could you move this one to https://github.com/vapor/sql? Thanks!
