### ISSUE TITLE
Issue with ConnectionPool::requestConnection?

### ISSUE THREAD

**Issue by foobarzap** [vapor/database-kit#34]
I ran into a deadlock situation on a single CPU virtual machine when using TokenAuthentication. The deadlock appeared in a controller that handles queries to my user table, more precisely when resolving a parameter like so: `return try req.parameters.next(User.Public.self)`.

I tried to break it down and the problem seems to be that a connection to the DB is requested twice. First request appears in `BearerAuthenticatable::authenticate` when the query for the token is set up; second (nested) request is performed when looking up the parameter.

The nested request can't be fulfilled because there is no free connection left in the pool. So the thread falls asleep and waits for a connection to become available - boom: now we are waiting for ourselve ....

Don't know how to fix it but to me it appears a bit suspicious that requestConnection returns a Future, meaning sometimes in the Future we'll establish a connection, but already marks it as not being available ...

Interestingly, the deadlock only occurs when resolving Parameters. If I perform other queries on the users's table (e.g. use `User.query(on:req) ...`), no deadlock occurs. So it could be that the real problem is not caused by DatabaseKit but lies in the implementation of `Model::make(for parameter: String, using container: Container)`.

Any ideas?

**Comment by tanner0101** [comment]
You can use [`DatabaseConnectionPoolConfig`](https://api.vapor.codes/database-kit/latest/DatabaseKit/Structs/DatabaseConnectionPoolConfig.html) to increase the number of connections each pool can have. 

In terms of why two connections are being requested for a single route, that's likely a problem with the logic [here](https://github.com/vapor/fluent/blob/master/Sources/Fluent/Model/Model.swift#L271-L278). I'll create a separate issue to track that.

**Comment by tanner0101** [comment]
Closing this in favor of: https://github.com/vapor/fluent/issues/486. Thanks for the report @foobarzap!
