### ISSUE TITLE
DatabaseLogger isn't quite powerful enough

### ISSUE THREAD

**Issue by 0xTim** [vapor/database-kit#35]
In my application, it's desirable that even the extremely debug-level logs that are database queries when database logging is enabled be redirected to an appropriate log output on a per-request basis - or more exactly, that it be possible to associate a given set of logged queries with a particular request. Currently, the only way this is possible is to "know" that `MySQLConnection` and `SQLiteConnection` have public logger properties that one can reset inside `request.withPooledConnection(to:) {}` closures. Needless to say, this is not very generic. Nor does it lend itself well to the dependency injection that the separation of `DatabaseLogger` and `DatabaseLogHandler` implies was a goal of this particular subsystem (to say nothing of the DI-heavy design of Vapor as a whole). I would suggest one of:

1) Make `public var logger: DatabaseLogger? { get }` a protocol requirement of `DatabaseConnection where Self.Database: LogSupporting`, which at least solves the problem of overriding the logger per-connection for any given database (except that `DatabaseConnection` doesn't have a `Self.Database`, so hm)
2) Have `DatabaseLogger` leverage Services to get its `DatabaseLogHandler` (which is what I already expected it to be doing and was surprised to find out otherwise!), which would if properly designed allow for using Request's `privateContainer` to override the logger per-request
3) Allow an optional `DatabaseLogHandler` to be passed to `with[Pooled]Connection(to:)` when `Database: LogSupporting`, which would override the logger for that connection only - this strikes me as the most threadsafe (and probably also easiest to implement) option, since it can leverage LogSupporting's `enableLogging(_:on:)` with the connection.

**Comment by tanner0101** [comment]
I like 1 and 2 the most. Leaning toward 2. It would be great to leverage the private container there. But 1 seems potentially more flexible.

**Comment by tanner0101** [comment]
In light of the new [Logging API](https://forums.swift.org/t/feedback-server-logging-api-with-revisions/19375) that has been approved by the server work group, logging integration can now be provided by each database package in a more generally useful way.

I'll keep this issue open here as a reminder, but the actual implementation work should be happening  in packages like [NIOPostgres](https://github.com/vapor-community/nio-postgres).
