### ISSUE TITLE
Better value printing

### ISSUE THREAD

**Issue by grosch** [vapor/database-kit#37]
For debugging I've enabled logging and I end up with something like this from my PostgreSQL query

> SELECT * FROM "v_orders" WHERE ("v_orders"."month" = $1) ORDER BY "v_orders"."due" DESC ["TIMESTAMP (binary) \0\u{02}\u{11}(÷_@\0)"]

That's not very usable as I have no idea what got passed to the `month` parameter.  Is there some way to enhance this so that it prints out the human readable value?

**Comment by tanner0101** [comment]
This is specific to each driver (they determine the description string). DatabaseKit just prints it. Please open on the respective repo, thanks!
