### ISSUE TITLE
connection pool storage options

### ISSUE THREAD

**Issue by tanner0101** [vapor/database-kit#46]
Connection pool could be expanded with additional storage or "sharing" options to allow for better control over the numbers of connections an application uses. 

- Thread: Each connection pool shares its connections with all other pools on the same thread. 
- Process: Each connection pool shares its connections with all other pools in the same process. This is similar to thread-sharing but requires locks for synchronizing access.
- Instance: Each connection pool has its own, private connections.

**Comment by MrMage** [comment]
For an example on sharing pooled connections across all event loops, have a look at 
https://gist.github.com/MrMage/8972472ee73ab7b7d506ffb1c2b6e42e.

**Comment by tanner0101** [comment]
This was for the most part implemented in #53. 

Process:
Sharing connections across a process is not reasonable given Vapor's design. Each connection stores a reference to its event loop, which should always be the Request's event loop. This allows for route handlers to be much more efficient and not need to change threads a lot. 

Thread:
There's a new `ThreadConnectionPool` type that, if shared across threads, will yield the same connection pool per thread.

Instance:
Initializing a new connection pool will not share storage with any other connection pools that have been created in the thread or process.
